on: [push]

name: Build

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ubuntu-latest-cargo-
      - name: Update Rust
        run: rustup update
      - run: rustup target add wasm32-unknown-unknown
      - name: trunk install
        continue-on-error: true
        run: cargo install --locked trunk
      - run: trunk build --release
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch dist/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: timetable.dolphin2410.me